# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: wordcount.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'wordcount.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fwordcount.proto\x1a\x1bgoogle/protobuf/empty.proto\"4\n\x10WordCountRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x12\n\nrequest_id\x18\x02 \x01(\t\"7\n\x11WordCountResponse\x12\x0e\n\x06output\x18\x01 \x01(\t\x12\x12\n\nlatency_ms\x18\x02 \x01(\x02\"\x1d\n\x0cHealthStatus\x12\r\n\x05\x61live\x18\x01 \x01(\x08\x32x\n\x10WordCountService\x12\x33\n\nCountWords\x12\x11.WordCountRequest\x1a\x12.WordCountResponse\x12/\n\x06Health\x12\x16.google.protobuf.Empty\x1a\r.HealthStatusb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'wordcount_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WORDCOUNTREQUEST']._serialized_start=48
  _globals['_WORDCOUNTREQUEST']._serialized_end=100
  _globals['_WORDCOUNTRESPONSE']._serialized_start=102
  _globals['_WORDCOUNTRESPONSE']._serialized_end=157
  _globals['_HEALTHSTATUS']._serialized_start=159
  _globals['_HEALTHSTATUS']._serialized_end=188
  _globals['_WORDCOUNTSERVICE']._serialized_start=190
  _globals['_WORDCOUNTSERVICE']._serialized_end=310
# @@protoc_insertion_point(module_scope)
